<a href="https://colab.research.google.com/github/asimthaha/Pytorch_fundamentals/blob/main/00_Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#
 **00 Pytorch Fundamnetals**

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__) #cuda version 118

2.1.0+cu121


## what are tensors?
###Types of tensors

tensors are created using torch.tensor()


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
vector.ndim

1

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX[1]

tensor([ 9, 10])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors
start with random number - look at data - update random number - and repeat

In [16]:
#random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0596, 0.7672, 0.6039, 0.7269],
        [0.7160, 0.0920, 0.3456, 0.9525],
        [0.7394, 0.8866, 0.1605, 0.6127]])

In [17]:
random_tensor.ndim

2

In [18]:
#create a random tensor with similar shape to an image tensor
image_tensor = torch.rand(size=(224,224,3))
# height, width, colour channel
image_tensor.shape, image_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [19]:
# tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones*random_tensor

tensor([[0.0596, 0.7672, 0.6039, 0.7269],
        [0.7160, 0.0920, 0.3456, 0.9525],
        [0.7394, 0.8866, 0.1605, 0.6127]])

In [23]:
ones.dtype

torch.float32

### creating a range of tensors

In [24]:
# use torch.arange()
oneToTen = torch.arange(start=0,end=10, step=2)
oneToTen

tensor([0, 2, 4, 6, 8])

In [25]:
# Creating tensors like
ten_zeros= torch.zeros_like(input=oneToTen)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor Data Types

In [26]:
float_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype=None,
                            device=None,
                            requires_grad=False)
float_tensor

tensor([3., 6., 9.])

In [27]:
#converting tesnor into another dtype
float16_tensor = float_tensor.type(torch.half)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_tensor*float16_tensor

tensor([ 9., 36., 81.])

## Getting Information from tensors(Tensor Attributes)

tensors not right dtype = use tensor.dtype

Tensors not right shape = use tensor.shape

Tensors not right device = use tensor.device

In [29]:
tensor = torch.rand(3,4)
tensor

tensor([[0.1508, 0.3806, 0.6631, 0.5521],
        [0.9601, 0.4371, 0.3752, 0.9077],
        [0.8359, 0.2780, 0.7779, 0.7450]])

In [30]:
tensor.dtype, tensor.shape, tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulating Tensors (Tensor Operations)

Addition
Subtraction
Multipilcation
Division
Matrix Multiplication

In [31]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [32]:
tensor*10

tensor([10, 20, 30])

In [33]:
tensor - 1

tensor([0, 1, 2])

In [34]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [35]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

two main ways

1 element wise
2 matrix multiplication(Dot Product)

In [36]:
#element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [37]:
#matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [38]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.72 ms, sys: 0 ns, total: 1.72 ms
Wall time: 2.24 ms


In [39]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.24 ms, sys: 44 µs, total: 1.28 ms
Wall time: 2.13 ms


tensor(14)

### errors in deep learning- shape erros

two rules


1 inner dimensions must match

(3,2) * (3,2) wont work
(2,3) * (3,2) vise versa will work

2 the resulting matrix has the shape of the outer dimension

for the above (2,2) will be the shape

In [40]:
torch.matmul(torch.rand(2,10), torch.rand(10,2))

tensor([[2.3871, 2.7413],
        [2.2579, 2.5766]])

In [41]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[3.1752, 3.2315, 3.1710],
        [1.6876, 2.4735, 1.5956],
        [2.1320, 2.1843, 2.0856]])

### Shape errors

In [42]:
# shape for matrix multi

tensor1 = torch.tensor([[1,2],[3,4],[5,6]])

tensor2 = torch.tensor([[7,10],[8,11],[9,12]])

In [43]:
#torch.mm() is same as torhc.matmul()

# torch.mm(tensor1, tensor2)

### To fix out matrix multi issues, we can manipulate the shape of a tensor using transpose



In [44]:
tensor2.T, tensor2.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [45]:
tensor2

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [46]:
torch.mm(tensor1, tensor2.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [47]:
torch.mm(tensor1, tensor2.T).shape

torch.Size([3, 3])

### Tensor Aggregration- min, max, sum, mean

In [48]:
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [50]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [51]:
# torch.mean() needs a float 32 dtype as input

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [52]:
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

### Reshaping, stacking, squeezing and unsqueezing tensors

Reshaping - reshape an input tensor to defined shape

view - return a view of an input tensor of certain shape and keep the same memory as the og tensor

stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

Squeeze - removes all `1` dimesions from a tensor

Unsqueeze - adds a `1` dimensions to a target tensor

Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [53]:
import torch

x= torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [54]:
# add an extra dimension

x_reshaped= x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
# x_reshaped = x.reshape(2,9)
# x_reshaped

In [56]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [57]:
# change the view
import torch

x= torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [58]:
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [59]:
x= torch.arange(1., 13.)
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [60]:
# change the view

z = x.view(1,12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

changing z changes x because a view of a tensor shares the same memmort as the origina tensor

In [61]:
z[:,0]=5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [62]:
# stacking tensors

x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.],
        [11., 11., 11., 11.],
        [12., 12., 12., 12.]])

In [63]:
#squeeze tensors

x= torch.zeros(2,1,2,1,2)
x, x.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [64]:
y = torch.squeeze(x)
y, y.shape

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [65]:
y = torch.squeeze(x, 0)
y , y.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [66]:
y = torch.squeeze(x, 1)
y , y.shape

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

In [67]:
y = torch.squeeze(x, 2)
y , y.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [68]:
print(f"Previous tensor: {x}")
print(f"Previous shape: {x.shape}")

# Remove extra dimension from x_reshaped
y = x.squeeze()
print(f"\nNew tensor: {y}")
print(f"New shape: {y.shape}")

Previous tensor: tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
Previous shape: torch.Size([2, 1, 2, 1, 2])

New tensor: tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
New shape: torch.Size([2, 2, 2])


In [69]:
# torch.unsqueeze() adds a singel dimension
z= x.unsqueeze(dim=0)
z.shape

torch.Size([1, 2, 1, 2, 1, 2])

In [70]:
z= x.unsqueeze(dim=1)
z.shape

torch.Size([2, 1, 1, 2, 1, 2])

In [71]:
# torch.permute() - rearranges the dimensions of a target tensor in specified order

x=torch.rand(2,3,5)
x.shape


torch.Size([2, 3, 5])

In [72]:
y = torch.permute(x, (2,0,1)).size()
y

torch.Size([5, 2, 3])

In [73]:
x_og = torch.rand(size=(224,224,3)) #(height, width, color channels)

# permute the og tensor to rearrange the axis (or dim) order
x_permuted = x_og.permute(2, 0, 1) #changes the data in a index to another index

print(f"previous shape: {x_og.shape}") #(height, width, color channels)
print(f"permuted shape: {x_permuted.shape}") #(color channels,height, width)

previous shape: torch.Size([224, 224, 3])
permuted shape: torch.Size([3, 224, 224])


## selecting data from tensor using indexing

indexign with pytorch is simliar to indexing in numpy

In [74]:
import torch

x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [75]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [76]:
x[0][0]
x[0,0]# same as above

tensor([1, 2, 3])

In [77]:
x[0][0][0]

tensor(1)

In [78]:
x[0][2][2]

tensor(9)

In [79]:
# you can also use ":" to select all of a target
x[:, 0]

tensor([[1, 2, 3]])

In [87]:
x[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [90]:
x[:,1,0:2]

tensor([[4, 5]])

In [91]:
x[0,0,:]

tensor([1, 2, 3])

## pytorch tensors and numpy

numpy is numerical computing library

numpy to pytorch tensor
torch.from_numpy(ndarray)

pytorch tensor to numpy
torch.Tensor.numpy()


In [106]:
# numpy array to tensor
import torch
import numpy as np

arr = np.arange(1.0,8.0) # by default numpy array has dtype as float64 so when conveting to tensor we might need to specify the dtype
tensor = torch.from_numpy(arr).type(torch.float32)
arr, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [107]:
#change the value of arr, what will do to tensor
arr = arr + 1
arr , tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [108]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [109]:
# change the tensor what happens to numpy
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reporducability (trying to take random out of random)

To reduce the randomness in neural netwokrs and pytorch comes the concept of a **random seed**

Essentialy what **random seed** does is flavour the randomness

In [113]:
import torch

a = torch.rand(3,4)
b = torch.rand(3,4)

print(a)
print(b)
print(a == b)

tensor([[0.8498, 0.3734, 0.8043, 0.5873],
        [0.2445, 0.1189, 0.1895, 0.3886],
        [0.3370, 0.8514, 0.5244, 0.5724]])
tensor([[0.6737, 0.5828, 0.2948, 0.1009],
        [0.6860, 0.5536, 0.4653, 0.7256],
        [0.1136, 0.3507, 0.8722, 0.9872]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [116]:
# random but reproducable tensors

import torch
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
d = torch.rand(3,4)

print(c)
print(d)
print(c==d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPU(and making faster computations)

GPUs = faster computation on numbers

### Getting a GPU

use google colab

In [1]:
#check for access in gpu using pytorch
import torch
torch.cuda.is_available()

True

In [2]:
#setup device adnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
#device agnostic codes

torch.cuda.device_count()

1

## putting tensors and models on the gpu
using a gpu results in faster computations

In [4]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


move tensor to gpu if available

In [5]:
tensorOnGpu = tensor.to(device)
tensorOnGpu

tensor([1, 2, 3], device='cuda:0')

### moving tensors back to cpu

if tensor is on GPU , cant tranform it to Numpy

to fix the GPU tensor with numpy issues, we can first set it to the CPU


In [8]:
tensor_back_on_cpu = tensorOnGpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])