<a href="https://colab.research.google.com/github/asimthaha/Pytorch_fundamentals/blob/main/00_Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#
 **00 Pytorch Fundamnetals**

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__) #cuda version 118

2.1.0+cu118


## what are tensors?
###Types of tensors

tensors are created using torch.tensor()


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector.ndim

1

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors
start with random number - look at data - update random number - and repeat

In [ ]:
#random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7747, 0.0530, 0.1921, 0.1631],
        [0.1115, 0.7532, 0.6095, 0.1052],
        [0.4256, 0.7720, 0.7990, 0.4754]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
image_tensor = torch.rand(size=(224,224,3))
# height, width, colour channel
image_tensor.shape, image_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [ ]:
# tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones*random_tensor

tensor([[0.7747, 0.0530, 0.1921, 0.1631],
        [0.1115, 0.7532, 0.6095, 0.1052],
        [0.4256, 0.7720, 0.7990, 0.4754]])

In [ ]:
ones.dtype

torch.float32

### creating a range of tensors

In [ ]:
# use torch.arange()
oneToTen = torch.arange(start=0,end=10, step=2)
oneToTen

tensor([0, 2, 4, 6, 8])

In [ ]:
# Creating tensors like
ten_zeros= torch.zeros_like(input=oneToTen)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor Data Types

In [ ]:
float_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype=None,
                            device=None,
                            requires_grad=False)
float_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
#converting tesnor into another dtype
float16_tensor = float_tensor.type(torch.half)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_tensor*float16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting Information from tensors(Tensor Attributes)

tensors not right dtype = use tensor.dtype

Tensors not right shape = use tensor.shape

Tensors not right device = use tensor.device

In [ ]:
tensor = torch.rand(3,4)
tensor

tensor([[0.6336, 0.9634, 0.7980, 0.1285],
        [0.4447, 0.4481, 0.2727, 0.5765],
        [0.0752, 0.7500, 0.5601, 0.2165]])

In [ ]:
tensor.dtype, tensor.shape, tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulating Tensors (Tensor Operations)

Addition
Subtraction
Multipilcation
Division
Matrix Multiplication

In [ ]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor - 1

tensor([0, 1, 2])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])