<a href="https://colab.research.google.com/github/asimthaha/Pytorch_fundamentals/blob/main/00_Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#
 **00 Pytorch Fundamnetals**

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__) #cuda version 118

2.1.0+cu118


## what are tensors?
###Types of tensors

tensors are created using torch.tensor()


In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
vector.ndim

1

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX[1]

tensor([ 9, 10])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors
start with random number - look at data - update random number - and repeat

In [16]:
#random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7097, 0.7274, 0.9691, 0.0509],
        [0.0819, 0.3891, 0.0665, 0.6788],
        [0.2462, 0.1193, 0.8026, 0.9625]])

In [17]:
random_tensor.ndim

2

In [18]:
#create a random tensor with similar shape to an image tensor
image_tensor = torch.rand(size=(224,224,3))
# height, width, colour channel
image_tensor.shape, image_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [19]:
# tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones*random_tensor

tensor([[0.7097, 0.7274, 0.9691, 0.0509],
        [0.0819, 0.3891, 0.0665, 0.6788],
        [0.2462, 0.1193, 0.8026, 0.9625]])

In [23]:
ones.dtype

torch.float32

### creating a range of tensors

In [24]:
# use torch.arange()
oneToTen = torch.arange(start=0,end=10, step=2)
oneToTen

tensor([0, 2, 4, 6, 8])

In [25]:
# Creating tensors like
ten_zeros= torch.zeros_like(input=oneToTen)
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor Data Types

In [26]:
float_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype=None,
                            device=None,
                            requires_grad=False)
float_tensor

tensor([3., 6., 9.])

In [27]:
#converting tesnor into another dtype
float16_tensor = float_tensor.type(torch.half)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_tensor*float16_tensor

tensor([ 9., 36., 81.])

### Getting Information from tensors(Tensor Attributes)

tensors not right dtype = use tensor.dtype

Tensors not right shape = use tensor.shape

Tensors not right device = use tensor.device

In [29]:
tensor = torch.rand(3,4)
tensor

tensor([[0.4895, 0.5853, 0.9143, 0.3507],
        [0.5382, 0.6767, 0.0335, 0.7485],
        [0.8397, 0.4866, 0.6628, 0.2983]])

In [30]:
tensor.dtype, tensor.shape, tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manipulating Tensors (Tensor Operations)

Addition
Subtraction
Multipilcation
Division
Matrix Multiplication

In [31]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [32]:
tensor*10

tensor([10, 20, 30])

In [33]:
tensor - 1

tensor([0, 1, 2])

In [34]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [35]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

two main ways

1 element wise
2 matrix multiplication(Dot Product)

In [36]:
#element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [37]:
#matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [38]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.6 ms, sys: 104 µs, total: 1.7 ms
Wall time: 2.12 ms


In [39]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 69 µs, sys: 0 ns, total: 69 µs
Wall time: 72.5 µs


tensor(14)

### errors in deep learning- shape erros

two rules


1 inner dimensions must match

(3,2) * (3,2) wont work
(2,3) * (3,2) vise versa will work

2 the resulting matrix has the shape of the outer dimension

for the above (2,2) will be the shape

In [44]:
torch.matmul(torch.rand(2,10), torch.rand(10,2))

tensor([[3.0611, 2.4549],
        [3.3888, 2.7282]])

In [45]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[3.7137, 2.9683, 2.3474],
        [2.4399, 1.8101, 1.6640],
        [3.5939, 3.3444, 2.6171]])

### Shape erros

In [47]:
# shape for matrix multi

tensor1 = torch.tensor([[1,2],[3,4],[5,6]])

tensor2 = torch.tensor([[7,10],[8,11],[9,12]])

In [48]:
#torch.mm() is same as torhc.matmul()

torch.mm(tensor1, tensor2)

RuntimeError: ignored

### to fix out matrix multi issues, we can manipulate the shape of on eof out tensors using transpose



In [51]:
tensor2.T, tensor2.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [50]:
tensor2

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [52]:
torch.mm(tensor1, tensor2.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [53]:
torch.mm(tensor1, tensor2.T).shape

torch.Size([3, 3])

## Tensor Aggregration- min, max, sum, mean

In [54]:
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [57]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [62]:
# torch.mean() needs a float 32 dtype as input

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [63]:
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

### positional min and max

In [65]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
x[0]

tensor(0)

In [68]:
# finds the position in the  tensor that has the minimum value
# returns index postion of the target
x.argmin()

tensor(0)

In [69]:
# finds the index in the tensor that has max vaue

x.argmax()

tensor(9)